<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class ClienteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Desactivar restricciones de clave foránea
        Schema::disableForeignKeyConstraints();

        // Truncar la tabla
        DB::table('Clientes')->truncate();

        // Datos de los clientes extraídos del SQL
        $clientes = [
            [
                'id_cliente' => 24,
                'nombre' => 'Juan',
                'apellido1' => 'Real',
                'apellido2' => 'López',
                'IBAN' => 'ES8011797674564484104052',
                'mail' => 'juan.perez@email.com',
                'telefono' => '600111222',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 0,
            ],
            [
                'id_cliente' => 25,
                'nombre' => 'Anna',
                'apellido1' => 'García',
                'apellido2' => 'Fernández',
                'IBAN' => 'ES8823361268043655689357',
                'mail' => 'ana.garcia@email.com',
                'telefono' => '600333444',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 0,
            ],
            [
                'id_cliente' => 26,
                'nombre' => 'Carlos',
                'apellido1' => 'Martínez',
                'apellido2' => 'Gómez',
                'IBAN' => 'ES9367829077082881698714',
                'mail' => 'carlos.martinez@email.com',
                'telefono' => '600555666',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 0,
            ],
            [
                'id_cliente' => 27,
                'nombre' => 'Laura',
                'apellido1' => 'Sánchez',
                'apellido2' => 'Ruiz',
                'IBAN' => 'ES7236306499431557358564',
                'mail' => 'laura.sanchez@email.com',
                'telefono' => '600777888',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 0,
            ],
            [
                'id_cliente' => 28,
                'nombre' => 'Pedro',
                'apellido1' => 'Díaz',
                'apellido2' => 'Morales',
                'IBAN' => 'ES5807462532893789651728',
                'mail' => 'pedro.diaz@email.com',
                'telefono' => '600999000',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 0,
            ],
            [
                'id_cliente' => 29,
                'nombre' => 'Marta',
                'apellido1' => 'Romero',
                'apellido2' => 'Navarro',
                'IBAN' => 'ES2728194090794761586849',
                'mail' => 'marta.romero@email.com',
                'telefono' => '601111222',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 0,
            ],
            [
                'id_cliente' => 30,
                'nombre' => 'Luis',
                'apellido1' => 'Torres',
                'apellido2' => 'Vega',
                'IBAN' => 'ES0450681446272439616458',
                'mail' => 'luis.torres@email.com',
                'telefono' => '601333444',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 31,
                'nombre' => 'Sofía',
                'apellido1' => 'Ramírez',
                'apellido2' => 'Cruz',
                'IBAN' => 'ES8055566282742863798375',
                'mail' => 'sofia.ramirez@email.com',
                'telefono' => '601555666',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 32,
                'nombre' => 'Diego',
                'apellido1' => 'Hernández',
                'apellido2' => 'Ortiz',
                'IBAN' => 'ES3919341374022616798736',
                'mail' => 'diego.hernandez@email.com',
                'telefono' => '601777888',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 0,
            ],
            [
                'id_cliente' => 33,
                'nombre' => 'Lucía',
                'apellido1' => 'Moreno',
                'apellido2' => 'Iglesias',
                'IBAN' => 'ES3870344873779186810777',
                'mail' => 'lucia.moreno@email.com',
                'telefono' => '601999000',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 35,
                'nombre' => 'Alberto',
                'apellido1' => 'Santos',
                'apellido2' => 'Pérez',
                'IBAN' => 'ES8033461610162766878800',
                'mail' => 'alberto.santos@email.com',
                'telefono' => '602111222',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 36,
                'nombre' => 'Isabel',
                'apellido1' => 'Vargas',
                'apellido2' => 'López',
                'IBAN' => 'ES2606321097504000548274',
                'mail' => 'isabel.vargas@email.com',
                'telefono' => '602333444',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 37,
                'nombre' => 'Fernando',
                'apellido1' => 'Castillo',
                'apellido2' => 'Ramírez',
                'IBAN' => 'ES9288120482002812363125',
                'mail' => 'fernando.castillo@email.com',
                'telefono' => '602555666',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 38,
                'nombre' => 'Elena',
                'apellido1' => 'Ríos',
                'apellido2' => 'Gómez',
                'IBAN' => 'ES1592401233782324439359',
                'mail' => 'elena.rios@email.com',
                'telefono' => '602777888',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 39,
                'nombre' => 'Ricardo',
                'apellido1' => 'Molina',
                'apellido2' => 'Fernández',
                'IBAN' => 'ES5741779672015844283530',
                'mail' => 'ricardo.molina@email.com',
                'telefono' => '602999000',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 40,
                'nombre' => 'Paula',
                'apellido1' => 'Alonso',
                'apellido2' => 'Sánchez',
                'IBAN' => 'ES2066004732411802076983',
                'mail' => 'paula.alonso@email.com',
                'telefono' => '603111222',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 41,
                'nombre' => 'Sergio',
                'apellido1' => 'Navarro',
                'apellido2' => 'Díaz',
                'IBAN' => 'ES9726857285974643597764',
                'mail' => 'sergio.navarro@email.com',
                'telefono' => '603333444',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 42,
                'nombre' => 'Marina',
                'apellido1' => 'Cruz',
                'apellido2' => 'Morales',
                'IBAN' => 'ES3793423574309775194201',
                'mail' => 'marina.cruz@email.com',
                'telefono' => '603555666',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 43,
                'nombre' => 'Javier',
                'apellido1' => 'Herrera',
                'apellido2' => 'Romero',
                'IBAN' => 'ES2832031205765913670828',
                'mail' => 'javier.herrera@email.com',
                'telefono' => '603777888',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 44,
                'nombre' => 'Natalia',
                'apellido1' => 'Ortiz',
                'apellido2' => 'Vega',
                'IBAN' => 'ES1955410494653629750326',
                'mail' => 'natalia.ortiz@email.com',
                'telefono' => '603999000',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 45,
                'nombre' => 'David',
                'apellido1' => 'Gómez',
                'apellido2' => 'Cruz',
                'IBAN' => 'ES1914368090441220353601',
                'mail' => 'david.gomez@email.com',
                'telefono' => '604111222',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 46,
                'nombre' => 'Cristina',
                'apellido1' => 'Pardo',
                'apellido2' => 'Fernández',
                'IBAN' => 'ES1138854091321967171793',
                'mail' => 'cristina.pardo@email.com',
                'telefono' => '604333444',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 47,
                'nombre' => 'Manuel',
                'apellido1' => 'Gil',
                'apellido2' => 'Ruiz',
                'IBAN' => 'ES5933262143698125051554',
                'mail' => 'manuel.gil@email.com',
                'telefono' => '604555666',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 48,
                'nombre' => 'Verónica',
                'apellido1' => 'Medina',
                'apellido2' => 'Moreno',
                'IBAN' => 'ES7634003435024267391625',
                'mail' => 'veronica.medina@email.com',
                'telefono' => '604777888',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 49,
                'nombre' => 'Pablo',
                'apellido1' => 'Serrano',
                'apellido2' => 'Iglesias',
                'IBAN' => 'ES0425423126863035174506',
                'mail' => 'pablo.serrano@email.com',
                'telefono' => '604999000',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 50,
                'nombre' => 'Laura',
                'apellido1' => 'Marín',
                'apellido2' => 'Ramos',
                'IBAN' => 'ES0347154356237927967772',
                'mail' => 'laura.marin@email.com',
                'telefono' => '605111222',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 51,
                'nombre' => 'José',
                'apellido1' => 'Domínguez',
                'apellido2' => 'López',
                'IBAN' => 'ES6725430134069458872238',
                'mail' => 'jose.dominguez@email.com',
                'telefono' => '605333444',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 52,
                'nombre' => 'Andrea',
                'apellido1' => 'Cabrera',
                'apellido2' => 'Martínez',
                'IBAN' => 'ES9453672620493441479039',
                'mail' => 'andrea.cabrera@email.com',
                'telefono' => '605555666',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 53,
                'nombre' => 'Raúl',
                'apellido1' => 'Santos',
                'apellido2' => 'Pérez',
                'IBAN' => 'ES6444546773624778960112',
                'mail' => 'raul.santos@email.com',
                'telefono' => '605777888',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 0,
            ],
            [
                'id_cliente' => 54,
                'nombre' => 'Clara',
                'apellido1' => 'Méndez',
                'apellido2' => 'Vega',
                'IBAN' => 'ES4590595853728349620774',
                'mail' => 'clara.mendez@email.com',
                'telefono' => '605999000',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 55,
                'nombre' => 'Antonio',
                'apellido1' => 'Fuentes',
                'apellido2' => 'Navarro',
                'IBAN' => 'ES8189148215529277988822',
                'mail' => 'antonio.fuentes@email.com',
                'telefono' => '606111222',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 56,
                'nombre' => 'Patricia',
                'apellido1' => 'Román',
                'apellido2' => 'Hernández',
                'IBAN' => 'ES0349717743693384096966',
                'mail' => 'patricia.roman@email.com',
                'telefono' => '606333444',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 57,
                'nombre' => 'Miguel',
                'apellido1' => 'Castro',
                'apellido2' => 'Ortiz',
                'IBAN' => 'ES8241474237615003309762',
                'mail' => 'miguel.castro@email.com',
                'telefono' => '606555666',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 58,
                'nombre' => 'Sonia',
                'apellido1' => 'Vega',
                'apellido2' => 'Ramos',
                'IBAN' => 'ES9800862794323258979141',
                'mail' => 'sonia.vega@email.com',
                'telefono' => '606777888',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 59,
                'nombre' => 'Adrián',
                'apellido1' => 'Blanco',
                'apellido2' => 'Gil',
                'IBAN' => 'ES6663769263852227820061',
                'mail' => 'adrian.blanco@email.com',
                'telefono' => '606999000',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 60,
                'nombre' => 'Raquel',
                'apellido1' => 'Mora',
                'apellido2' => 'Serrano',
                'IBAN' => 'ES6316294092316147336318',
                'mail' => 'raquel.mora@email.com',
                'telefono' => '607111222',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 61,
                'nombre' => 'Héctor',
                'apellido1' => 'Campos',
                'apellido2' => 'Pardo',
                'IBAN' => 'ES1160409413688870998172',
                'mail' => 'hector.campos@email.com',
                'telefono' => '607333444',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 62,
                'nombre' => 'Natalie',
                'apellido1' => 'Vidal',
                'apellido2' => 'Gómez',
                'IBAN' => 'ES0968531768798330685808',
                'mail' => 'natalie.vidal@email.com',
                'telefono' => '607555666',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 63,
                'nombre' => 'Iván',
                'apellido1' => 'Luna',
                'apellido2' => 'Morales',
                'IBAN' => 'ES9125992047559243139523',
                'mail' => 'ivan.luna@email.com',
                'telefono' => '607777888',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 0,
            ],
            [
                'id_cliente' => 64,
                'nombre' => 'Sandra',
                'apellido1' => 'Ramos',
                'apellido2' => 'Cruz',
                'IBAN' => 'ES5450542607154782667977',
                'mail' => 'sandra.ramos@email.com',
                'telefono' => '607999000',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 65,
                'nombre' => 'Diego',
                'apellido1' => 'Reyes',
                'apellido2' => 'Molina',
                'IBAN' => 'ES4335455431932865488133',
                'mail' => 'diego.reyes@email.com',
                'telefono' => '608111222',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 66,
                'nombre' => 'Mónica',
                'apellido1' => 'Pérez',
                'apellido2' => 'Sánchez',
                'IBAN' => 'ES1249742824419791561992',
                'mail' => 'monica.perez@email.com',
                'telefono' => '608333444',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 67,
                'nombre' => 'Francisco',
                'apellido1' => 'Ortiz',
                'apellido2' => 'López',
                'IBAN' => 'ES4128131786412439589564',
                'mail' => 'francisco.ortiz@email.com',
                'telefono' => '608555666',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 68,
                'nombre' => 'Lorena',
                'apellido1' => 'Vega',
                'apellido2' => 'Fernández',
                'IBAN' => 'ES9541498119084819286747',
                'mail' => 'lorena.vega@email.com',
                'telefono' => '608777888',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 69,
                'nombre' => 'Alfonso',
                'apellido1' => 'Cano',
                'apellido2' => 'Navarro',
                'IBAN' => 'ES2898432913928395034783',
                'mail' => 'alfonso.cano@email.com',
                'telefono' => '608999000',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 70,
                'nombre' => 'Julia',
                'apellido1' => 'Guerrero',
                'apellido2' => 'Gómez',
                'IBAN' => 'ES2162128056105960204800',
                'mail' => 'julia.guerrero@email.com',
                'telefono' => '609111222',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 71,
                'nombre' => 'Raúl',
                'apellido1' => 'Pérez',
                'apellido2' => 'Ruiz',
                'IBAN' => 'ES3731546369469791431578',
                'mail' => 'raul.perez@email.com',
                'telefono' => '609333444',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 72,
                'nombre' => 'Teresa',
                'apellido1' => 'Santos',
                'apellido2' => 'López',
                'IBAN' => 'ES3573581700509158168432',
                'mail' => 'teresa.santos@email.com',
                'telefono' => '609555666',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 73,
                'nombre' => 'Gonzalo',
                'apellido1' => 'Vargas',
                'apellido2' => 'Fernández',
                'IBAN' => 'ES6650312950866993587667',
                'mail' => 'gonzalo.vargas@email.com',
                'telefono' => '609777888',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 0,
            ],
            [
                'id_cliente' => 74,
                'nombre' => 'Inés',
                'apellido1' => 'Martínez',
                'apellido2' => 'Romero',
                'IBAN' => 'ES6135392773351828198646',
                'mail' => 'ines.martinez@email.com',
                'telefono' => '609999000',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 75,
                'nombre' => 'Mario',
                'apellido1' => 'López',
                'apellido2' => 'Morales',
                'IBAN' => 'ES9614947988873656186468',
                'mail' => 'mario.lopez@email.com',
                'telefono' => '610111222',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 76,
                'nombre' => 'Cecilia',
                'apellido1' => 'Fernández',
                'apellido2' => 'Navarro',
                'IBAN' => 'ES1848133792342304976731',
                'mail' => 'cecilia.fernandez@email.com',
                'telefono' => '610333444',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 77,
                'nombre' => 'Tomás',
                'apellido1' => 'Hernández',
                'apellido2' => 'Cruz',
                'IBAN' => 'ES8429843701824838543638',
                'mail' => 'tomas.hernandez@email.com',
                'telefono' => '610555666',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 78,
                'nombre' => 'Olga',
                'apellido1' => 'Sánchez',
                'apellido2' => 'Vega',
                'IBAN' => 'ES1390097523383202404312',
                'mail' => 'olga.sanchez@email.com',
                'telefono' => '610777888',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 79,
                'nombre' => 'Iván',
                'apellido1' => 'Moreno',
                'apellido2' => 'Ramírez',
                'IBAN' => 'ES2825078529215935786243',
                'mail' => 'ivan.moreno@email.com',
                'telefono' => '610999000',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 80,
                'nombre' => 'Claudia',
                'apellido1' => 'Romero',
                'apellido2' => 'Gómez',
                'IBAN' => 'ES0472295769679285754935',
                'mail' => 'claudia.romero@email.com',
                'telefono' => '611111222',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 81,
                'nombre' => 'Jorge',
                'apellido1' => 'Torres',
                'apellido2' => 'López',
                'IBAN' => 'ES8224633834938124595689',
                'mail' => 'jorge.torres@email.com',
                'telefono' => '611333444',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 82,
                'nombre' => 'Verónica',
                'apellido1' => 'Molina',
                'apellido2' => 'Fernández',
                'IBAN' => 'ES1286148329887567710438',
                'mail' => 'veronica.molina@email.com',
                'telefono' => '611555666',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 83,
                'nombre' => 'Andrés',
                'apellido1' => 'González',
                'apellido2' => 'Navarro',
                'IBAN' => 'ES7350297513233429516767',
                'mail' => 'andres.gonzalez@email.com',
                'telefono' => '611777888',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 84,
                'nombre' => 'Natalia',
                'apellido1' => 'López',
                'apellido2' => 'Ramírez',
                'IBAN' => 'ES4634438788891377883462',
                'mail' => 'natalia.lopez@email.com',
                'telefono' => '611999000',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 85,
                'nombre' => 'Raúl',
                'apellido1' => 'Hernández',
                'apellido2' => 'Serrano',
                'IBAN' => 'ES6452436902223289058763',
                'mail' => 'raul.hernandez@email.com',
                'telefono' => '612111222',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 86,
                'nombre' => 'Sandra',
                'apellido1' => 'Gómez',
                'apellido2' => 'Pérez',
                'IBAN' => 'ES5057157656349740832876',
                'mail' => 'sandra.gomez@email.com',
                'telefono' => '612333444',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 87,
                'nombre' => 'Luis',
                'apellido1' => 'Vega',
                'apellido2' => 'Martínez',
                'IBAN' => 'ES3693963673918803338361',
                'mail' => 'luis.vega@email.com',
                'telefono' => '612555666',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 88,
                'nombre' => 'Carla',
                'apellido1' => 'Navarro',
                'apellido2' => 'Ruiz',
                'IBAN' => 'ES5932494939705317162025',
                'mail' => 'carla.navarro@email.com',
                'telefono' => '612777888',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
            [
                'id_cliente' => 89,
                'nombre' => 'Diego',
                'apellido1' => 'Cabrera',
                'apellido2' => 'Gómez',
                'IBAN' => 'ES5282889359825461337498',
                'mail' => 'diego.cabrera@email.com',
                'telefono' => '612999000',
                'password' => '0000',
                'remember_token' => null,
                'estado' => 1,
            ],
        ];

        // Hash de las contraseñas individualmente antes de insertar
        foreach ($clientes as &$c) {
            $c['password'] = Hash::make($c['password'], ['rounds' => 6]); // rounds bajos para seed rápido
        }

        // Insertar todos los clientes de golpe
        DB::table('Clientes')->insert($clientes);

        // Reactivar restricciones de clave foránea
        Schema::enableForeignKeyConstraints();
    }
}