<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReservaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Deshabilitar restricciones de clave foránea
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Truncar la tabla antes de insertar
        DB::table('Reservas')->truncate();

        // Datos de las reservas extraídos del SQL
        $reservas = [
            [
                'id' => 30,
                'fk_id_planificacion' => 27,
                'fk_id_cliente' => 69,
                'fecha_reserva' => '2025-10-24',
                'estado' => -1,
            ],
            [
                'id' => 31,
                'fk_id_planificacion' => 25,
                'fk_id_cliente' => 37,
                'fecha_reserva' => '2025-10-30',
                'estado' => -1,
            ],
            [
                'id' => 32,
                'fk_id_planificacion' => 28,
                'fk_id_cliente' => 52,
                'fecha_reserva' => '2025-10-30',
                'estado' => -1,
            ],
            [
                'id' => 34,
                'fk_id_planificacion' => 27,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-10-31',
                'estado' => -1,
            ],
            [
                'id' => 40,
                'fk_id_planificacion' => 42,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-10-31',
                'estado' => -1,
            ],
            [
                'id' => 41,
                'fk_id_planificacion' => 42,
                'fk_id_cliente' => 59,
                'fecha_reserva' => '2025-10-31',
                'estado' => -1,
            ],
            [
                'id' => 42,
                'fk_id_planificacion' => 42,
                'fk_id_cliente' => 89,
                'fecha_reserva' => '2025-10-31',
                'estado' => -1,
            ],
            [
                'id' => 43,
                'fk_id_planificacion' => 14,
                'fk_id_cliente' => 59,
                'fecha_reserva' => '2025-11-06',
                'estado' => -1,
            ],
            [
                'id' => 44,
                'fk_id_planificacion' => 14,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-06',
                'estado' => -1,
            ],
            [
                'id' => 45,
                'fk_id_planificacion' => 14,
                'fk_id_cliente' => 59,
                'fecha_reserva' => '2025-11-06',
                'estado' => -1,
            ],
            [
                'id' => 46,
                'fk_id_planificacion' => 24,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-06',
                'estado' => -1,
            ],
            [
                'id' => 47,
                'fk_id_planificacion' => 24,
                'fk_id_cliente' => 59,
                'fecha_reserva' => '2025-11-06',
                'estado' => -1,
            ],
            [
                'id' => 48,
                'fk_id_planificacion' => 25,
                'fk_id_cliente' => 69,
                'fecha_reserva' => '2025-11-06',
                'estado' => -1,
            ],
            [
                'id' => 52,
                'fk_id_planificacion' => 39,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-07',
                'estado' => 0,
            ],
            [
                'id' => 53,
                'fk_id_planificacion' => 39,
                'fk_id_cliente' => 59,
                'fecha_reserva' => '2025-11-07',
                'estado' => 0,
            ],
            [
                'id' => 54,
                'fk_id_planificacion' => 39,
                'fk_id_cliente' => 59,
                'fecha_reserva' => '2025-11-07',
                'estado' => -1,
            ],
            [
                'id' => 55,
                'fk_id_planificacion' => 39,
                'fk_id_cliente' => 89,
                'fecha_reserva' => '2025-11-07',
                'estado' => -1,
            ],
            [
                'id' => 56,
                'fk_id_planificacion' => 39,
                'fk_id_cliente' => 61,
                'fecha_reserva' => '2025-11-07',
                'estado' => -1,
            ],
            [
                'id' => 57,
                'fk_id_planificacion' => 24,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-13',
                'estado' => -1,
            ],
            [
                'id' => 58,
                'fk_id_planificacion' => 24,
                'fk_id_cliente' => 59,
                'fecha_reserva' => '2025-11-13',
                'estado' => -1,
            ],
            [
                'id' => 59,
                'fk_id_planificacion' => 24,
                'fk_id_cliente' => 89,
                'fecha_reserva' => '2025-11-13',
                'estado' => -1,
            ],
            [
                'id' => 60,
                'fk_id_planificacion' => 39,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 61,
                'fk_id_planificacion' => 28,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 62,
                'fk_id_planificacion' => 38,
                'fk_id_cliente' => 59,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 63,
                'fk_id_planificacion' => 28,
                'fk_id_cliente' => 57,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 64,
                'fk_id_planificacion' => 39,
                'fk_id_cliente' => 51,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 65,
                'fk_id_planificacion' => 50,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => 0,
            ],
            [
                'id' => 66,
                'fk_id_planificacion' => 50,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => 0,
            ],
            [
                'id' => 67,
                'fk_id_planificacion' => 50,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => 0,
            ],
            [
                'id' => 68,
                'fk_id_planificacion' => 50,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => 0,
            ],
            [
                'id' => 69,
                'fk_id_planificacion' => 50,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => 0,
            ],
            [
                'id' => 70,
                'fk_id_planificacion' => 50,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => 0,
            ],
            [
                'id' => 71,
                'fk_id_planificacion' => 50,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => 0,
            ],
            [
                'id' => 72,
                'fk_id_planificacion' => 50,
                'fk_id_cliente' => 59,
                'fecha_reserva' => '2025-11-14',
                'estado' => 0,
            ],
            [
                'id' => 73,
                'fk_id_planificacion' => 50,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => 0,
            ],
            [
                'id' => 74,
                'fk_id_planificacion' => 50,
                'fk_id_cliente' => 59,
                'fecha_reserva' => '2025-11-14',
                'estado' => 0,
            ],
            [
                'id' => 75,
                'fk_id_planificacion' => 26,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => 0,
            ],
            [
                'id' => 76,
                'fk_id_planificacion' => 26,
                'fk_id_cliente' => 37,
                'fecha_reserva' => '2025-11-14',
                'estado' => 0,
            ],
            [
                'id' => 77,
                'fk_id_planificacion' => 26,
                'fk_id_cliente' => 89,
                'fecha_reserva' => '2025-11-14',
                'estado' => 0,
            ],
            [
                'id' => 78,
                'fk_id_planificacion' => 26,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 79,
                'fk_id_planificacion' => 28,
                'fk_id_cliente' => 52,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 80,
                'fk_id_planificacion' => 42,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => 0,
            ],
            [
                'id' => 81,
                'fk_id_planificacion' => 27,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 82,
                'fk_id_planificacion' => 26,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 83,
                'fk_id_planificacion' => 26,
                'fk_id_cliente' => 59,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 84,
                'fk_id_planificacion' => 27,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 85,
                'fk_id_planificacion' => 27,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 86,
                'fk_id_planificacion' => 28,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 87,
                'fk_id_planificacion' => 27,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 88,
                'fk_id_planificacion' => 39,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 89,
                'fk_id_planificacion' => 39,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 90,
                'fk_id_planificacion' => 39,
                'fk_id_cliente' => 59,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 91,
                'fk_id_planificacion' => 39,
                'fk_id_cliente' => 89,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 92,
                'fk_id_planificacion' => 38,
                'fk_id_cliente' => 61,
                'fecha_reserva' => '2025-11-14',
                'estado' => -1,
            ],
            [
                'id' => 93,
                'fk_id_planificacion' => 24,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-20',
                'estado' => -1,
            ],
            [
                'id' => 94,
                'fk_id_planificacion' => 24,
                'fk_id_cliente' => 59,
                'fecha_reserva' => '2025-11-20',
                'estado' => -1,
            ],
            [
                'id' => 95,
                'fk_id_planificacion' => 24,
                'fk_id_cliente' => 89,
                'fecha_reserva' => '2025-11-20',
                'estado' => 0,
            ],
            [
                'id' => 96,
                'fk_id_planificacion' => 39,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-21',
                'estado' => -1,
            ],
            [
                'id' => 97,
                'fk_id_planificacion' => 38,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-21',
                'estado' => -1,
            ],
            [
                'id' => 98,
                'fk_id_planificacion' => 28,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-21',
                'estado' => -1,
            ],
            [
                'id' => 99,
                'fk_id_planificacion' => 39,
                'fk_id_cliente' => 59,
                'fecha_reserva' => '2025-11-21',
                'estado' => -1,
            ],
            [
                'id' => 100,
                'fk_id_planificacion' => 26,
                'fk_id_cliente' => 40,
                'fecha_reserva' => '2025-11-28',
                'estado' => -1,
            ],
            [
                'id' => 101,
                'fk_id_planificacion' => 28,
                'fk_id_cliente' => 52,
                'fecha_reserva' => '2025-11-28',
                'estado' => -1,
            ],
            [
                'id' => 102,
                'fk_id_planificacion' => 26,
                'fk_id_cliente' => 57,
                'fecha_reserva' => '2025-11-28',
                'estado' => -1,
            ],
            [
                'id' => 103,
                'fk_id_planificacion' => 27,
                'fk_id_cliente' => 89,
                'fecha_reserva' => '2025-11-28',
                'estado' => -1,
            ],
            [
                'id' => 104,
                'fk_id_planificacion' => 27,
                'fk_id_cliente' => 37,
                'fecha_reserva' => '2025-11-28',
                'estado' => -1,
            ],
            [
                'id' => 105,
                'fk_id_planificacion' => 38,
                'fk_id_cliente' => 70,
                'fecha_reserva' => '2025-11-28',
                'estado' => -1,
            ],
            [
                'id' => 106,
                'fk_id_planificacion' => 38,
                'fk_id_cliente' => 52,
                'fecha_reserva' => '2025-11-28',
                'estado' => -1,
            ],
        ];

        // Insertar los datos
        DB::table('Reservas')->insert($reservas);

        // Rehabilitar restricciones de clave foránea
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}